services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/bycatch_thesis:latest
    command: bash
    environment:
      BITBUCKET_API_TOKEN: $BITBUCKET_API_TOKEN
      BITBUCKET_EMAIL: $BITBUCKET_EMAIL
    volumes:
      - $PWD:/workdir
    depends_on:
      data:
        condition: service_completed_successfully

  data:
    image: islasgeci/vessel_data:latest
    volumes:
      - ./data/external:/data_container
    command: sh -c "mkdir --parents /data_container && cp --archive --verbose /data/. /data_container"
