matrix:

- name: markdown-in-spanish
  aspell:
    lang: es
    ignore-case: true
    mode: markdown
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  sources:
  - '0?_*.md'
  default_encoding: utf-8

- name: markdown-in-english
  aspell:
    lang: en
    ignore-case: true
    mode: markdown
  dictionary:
    wordlists:
    - .github/config/.wordlist.txt
    encoding: utf-8
  sources:
  - '1?_*.md'
  default_encoding: utf-8
