name: Check spelling and style
on:
  push:
    branches:
      - develop
jobs:

  check:
    name: Check manuscripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Docker image
        run: docker pull islasgeci/bycatch_thesis:latest
      - name: Run spellcheck
        run: docker run --volume $PWD:/workdir islasgeci/bycatch_thesis:latest src/check_spelling.sh
      - name: Check Paper 1 style
        run: docker run --volume $PWD:/workdir islasgeci/bycatch_thesis:latest src/check_manuscript_style.sh "1?_*.md"
      - name: Check Paper 2 style
        run: docker run --volume $PWD:/workdir islasgeci/bycatch_thesis:latest src/check_manuscript_style.sh "2?_*.md"