name: Render
on: push
jobs:

  render-draft:
    name: Render draft
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: islasgeci/bycatch_thesis:latest
        outputs: type=docker,dest=/tmp/image.tar
    - name: Build draft
      run: |
        docker run islasgeci/bycatch_thesis make all
    - name: Upload draft
      uses: actions/upload-artifact@main
      with:
        name: bycatch
        path: |
          reports/*.pdf
          reports/*.docx
