name: Results
on: push
jobs:

  generate-results:
    name: Generate results
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./docker-compose.yml"
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
    - name: Generate trips summary
      run: |
        docker compose run islasgeci make data/processed/trips_summary.csv
    - name: Upload results
      uses: actions/upload-artifact@main
      with:
        name: results
        path: |
          data/processed/*.csv
