name: Results
on: push
jobs:

  generate-results:
    name: Generate results
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Build docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: islasgeci/bycatch_thesis:latest
    - name: Generate trips summary
      env:
        BITBUCKET_USERNAME: ${{ secrets.BITBUCKET_USERNAME }}
        BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
      run: |
        docker run --volume $PWD:/workdir --env BITBUCKET_USERNAME=$BITBUCKET_USERNAME --env BITBUCKET_PASSWORD=$BITBUCKET_PASSWORD islasgeci/bycatch_thesis make data/processed/trips_summary.csv
    - name: Upload results
      uses: actions/upload-artifact@main
      with:
        name: results
        path: |
          data/processed/*.csv
